name: 🚀 Auto Deploy to Ubuntu via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🔧 Deploy Exam-main to AWS Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "👉 Loyihani yuklab olish yoki yangilash..."
            cd /home/${{ secrets.SERVER_USER }}

            if [ -d "Exam-main" ]; then
              cd Exam-main
              git reset --hard
              git clean -fd
              git pull origin main
            else
              git clone https://github.com/exam-main/Exam-main.git
              cd Exam-main
            fi

            echo "🧼 Docker containerlarni to'xtatish..."
            docker compose down || true

            echo "📦 Docker build va up qilish..."
            docker compose up -d --build

            echo "✅ Deploy tugadi!"
